### ISSUE TITLE
添加端口映射时，判断HTTP协议的条件有问题

### ISSUE THREAD

**Issue by mrhuangyong** [dromara/neutrino-proxy#3]
<img width="1435" alt="image" src="https://github.com/dromara/neutrino-proxy/assets/20205636/ee8093f8-897c-4a7b-b94f-2d1c96f94776">

**Comment by aoshiguchen** [comment]
不好意思，因为主推gitee，没有及时关注github消息。 这个问题已经修复过了，请更新下版本
